config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :accounts, only: [:index] do
      resources :transactions, only: [:index]
    end
    resources :transactions, only: [:index, :update]
  end
  resources :direct, only: [:index]

  resources :messages, only: [:index, :create] do
    collection do
      get :chat
      get :clear
    end
  end

  resources :ship2myid, only: [:index]

  resources :streaming, only: [:index, :create]

  resources :charge, only: [:new, :create, :index]

  resources :calendars, only: [:new] do
    collection do
      post :index
    end
  end

  resources :reports, only: [:new, :index, :create, :show]
  resources :icons, only: [:new, :create, :show]
  resources :todo, only: [:index]

  root to: 'streaming#index'
end

app/controllers/streaming_controller.rb
class StreamingController < ApplicationController
  include ActionController::Live

  def index
  end

  def create
    # Thread.new do
    #   rest_client = Twitter::REST::Client.new do |config|
    #     config.consumer_key = 'EIStq4153oVgWxDWcb6EqQsbN'
    #     config.consumer_secret = 'LLqquBoXdQPk8GvnEEOp1yDE0as7dOF2sLj5iy9O2p7dw0TXbl'
    #     config.access_token = '2842505062-1tCpOgF7OwGV8PX2c3SoW9uey7IXWkTQfFXHgkb'
    #     config.access_token_secret = 'KobBUAAnvZai6mIut0FyueRqzr44aDM065k6LjiEzL3Nd'
    #   end
    #   3.times do
    #     sleep 2
    #     rest_client.update(('a'..'z').to_a.shuffle[0, 8].join)
    #   end
    #   Thread.stop
    # end

    client = Twitter::Streaming::Client.new do |config|
      config.consumer_key = 'EIStq4153oVgWxDWcb6EqQsbN'
      config.consumer_secret = 'LLqquBoXdQPk8GvnEEOp1yDE0as7dOF2sLj5iy9O2p7dw0TXbl'
      config.access_token = '2842505062-1tCpOgF7OwGV8PX2c3SoW9uey7IXWkTQfFXHgkb'
      config.access_token_secret = 'KobBUAAnvZai6mIut0FyueRqzr44aDM065k6LjiEzL3Nd'
    end
    client.filter(track: 'twitter, api') do |object|
      puts object.text if object.is_a?(Twitter::Tweet)
    end
    #@tweets = []
    # client.user do |object|
    #   if object.is_a?(Twitter::Tweet)
    #     @tweets << Tweet.create(text: object.text, url: object.url.to_s)
    #     if @tweets.count > 2
    #       break
    #     end
    #   end
    # end
  end

end

app/views/streaming/create.erb
<div class="alert alert-success" role="alert">
  Tweets are listed below
</div>
<br>
<% @tweets.each do |tweet| %>
    <div class="well">
      Tweet body: <%= tweet.text %>
      <br>
      Tweet <%= link_to 'url', tweet.url.to_s, target: '_blank' %>
    </div>
<% end %>

app/views/streaming/index.erb
<h2 class="text-center">Twitter streaming example</h2>

<p>
  Click the button to start streaming.<br>
  <strong>You will need to wait for 5 seconds to see the results</strong><br>
  App will post 3 random tweets to twitter through API.<br>
  Then it will get this tweets through <strong>user streaming twitter API</strong> and render them.<br>
  Url of each tweet will be displayed to ensure this is not fake.
</p>

<%= link_to 'Start', streaming_index_path, method: 'post', class: 'btn btn-success' %>