config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :accounts, only: [:index] do
      resources :transactions, only: [:index]
    end
    resources :transactions, only: [:index, :update]
  end
  resources :direct, only: [:index]

  resources :messages, only: [:index, :create] do
    collection do
      get :chat
      get :clear
    end
  end

  resources :ship2myid, only: [:index]

  resources :streaming, only: [:index, :create]

  resources :charge, only: [:new, :create, :index]

  resources :calendars, only: [:new] do
    collection do
      post :index
    end
  end

  resources :reports, only: [:new, :index, :create, :show]
  resources :icons, only: [:new, :create, :show]
  resources :todo, only: [:index]

  root to: 'streaming#index'
end

app/models/report.rb
class Report < ActiveRecord::Base
  validates :first_field, presence: true
  validates :second_field, presence: true
  validates :third_field, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
  end

  def create
    r = Report.new(report_params)
    if r.save
      redirect_to reports_path
    else
      @errors = r.errors.full_messages
      render 'new'
    end
  end

  def show
    @report = Report.find(params[:id])
    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"report-#{@report.id}.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  private
  def report_params
    params.require(:report).permit(:first_field, :second_field, :third_field)
  end
end

app/views/reports/index.html.erb
<h1>Reports</h1>
<table class="table table-responsive">
  <thead>
    <tr>
      <th>
        First field
      </th>
      <th>
        Second field
      </th>
      <th>
        Third field
      </th>
      <th>
        Created at
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
        <tr>
          <td>
            <%= report.first_field %>
          </td>
          <td>
            <%= report.second_field %>
          </td>
          <td>
            <%= report.third_field %>
          </td>
          <td>
            <%= report.created_at.strftime('%-d/%-m/%Y %H:%M') %>
          </td>
          <td>
            <%= link_to 'Download CSV', report_path(report,format: :csv), class: 'btn btn-success' %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<h1>Create report</h1>
<% unless @errors.nil? %>
    <% @errors.each do |error| %>
        <div class='alert alert-dismissible alert-danger' role='alert'>
          <button class="close" type="button" data-dismiss="alert">
            <span area-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <%= error %>
        </div>
    <% end %>
<% end %>
<%= form_for Report.new do |f| %>
    <div class="form-group">
      <%= f.label :first_field %>
      <%= f.text_field :first_field, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :second_field %>
      <%= f.text_field :second_field, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :third_field %>
      <%= f.text_field :third_field, class: 'form-control' %>
    </div>
    <%= f.submit 'Save', class: 'btn btn-block btn-lg btn-success' %>
<% end %>

app/views/reports/show.csv.erb
<%= CSV.generate_line ['First field', 'Second field', 'Third field'] %>
<%= CSV.generate_line [@report.first_field, @report.second_field, @report.third_field] %>